import { ChannelType, EmbedBuilder, type Client, type TextChannel } from "discord.js";
import { getCountry } from "../config/countries.js";
import type { CountryAssignmentRepository } from "../database/countryAssignmentRepository.js";
import type { ResultRepository } from "../database/resultRepository.js";
import type { SubmissionRepository } from "../database/submissionRepository.js";
import type { VoteRepository } from "../database/voteRepository.js";
import type { ResultSession } from "../types/result.js";
import type { VoteEntry } from "../types/vote.js";
import type { GuildConfigService } from "./guildConfigService.js";

export class ResultService {
  constructor(private client:Client,private configs:GuildConfigService,private results:ResultRepository,private votes:VoteRepository,private submissions:SubmissionRepository,private assignments:CountryAssignmentRepository){}
  prepare(guildId:string){ if(this.configs.get(guildId).votingOpen) throw new Error("VOTING_OPEN"); const ballots=this.votes.listSubmitted(guildId); if(!ballots.length)throw new Error("NO_BALLOTS"); return this.results.prepare(guildId,ballots,this.submissions.listApproved(guildId).map(s=>s.countryCode)); }
  async start(guildId:string){ const s=this.results.findCurrent(guildId); if(!s||s.status!=='PREPARED')throw new Error("NOT_PREPARED");const ch=await this.channel(guildId,'results');await this.channel(guildId,'scoreboard'); if(!this.results.transition(guildId,'PREPARED','RUNNING'))throw new Error('CONFLICT'); await this.syncScoreboard(guildId); await ch.send({embeds:[new EmbedBuilder().setTitle('🎆 Sonuç Gecesi Başlıyor').setDescription(`**${s.revealOrder.length}** ülkenin oyları sırayla açıklanacak.`).setColor(0x9b59b6)]}); return this.results.findCurrent(guildId)!; }
  pause(guildId:string){return this.results.transition(guildId,'RUNNING','PAUSED');} resume(guildId:string){return this.results.transition(guildId,'PAUSED','RUNNING');} finish(guildId:string){const s=this.results.findCurrent(guildId); return s&&(s.status==='RUNNING'||s.status==='PAUSED')?this.results.transition(guildId,s.status,'FINISHED'):false;}
  async next(guildId:string){ const advanced=this.results.next(guildId); if(!advanced)return null; const c=getCountry(advanced.ballot.voterCountryCode); const lines=[...advanced.ballot.entries].sort((a,b)=>a.points-b.points).map(e=>{const t=getCountry(e.targetCountryCode);return `${e.points===12?'**12**':e.points} — ${t?.flag??'🌍'} ${t?.nameTr??e.targetCountryCode}`;}); const ch=await this.channel(guildId,'results'); await ch.send({embeds:[new EmbedBuilder().setTitle(`${c?.flag??'🌍'} ${c?.nameTr??advanced.ballot.voterCountryCode} oylarını açıkladı`).setDescription(lines.join('\n')).setColor(0xf1c40f)]}); await this.syncScoreboard(guildId); if(advanced.finished)await this.announceWinner(guildId,advanced.session,ch); return advanced; }
  totals(session:ResultSession,revealedOnly=true){ const allowed=new Set(session.revealOrder.slice(0,revealedOnly?session.currentIndex:session.revealOrder.length)); const map=new Map<string,{countryCode:string,total:number,twelve:number,ten:number,voters:Set<string>}>();for(const code of session.targetCountries)map.set(code,{countryCode:code,total:0,twelve:0,ten:0,voters:new Set<string>()}); for(const b of session.ballots){if(!allowed.has(b.voterCountryCode))continue;for(const e of b.entries){const v=map.get(e.targetCountryCode)??{countryCode:e.targetCountryCode,total:0,twelve:0,ten:0,voters:new Set<string>()};v.total+=e.points;if(e.points===12)v.twelve++;if(e.points===10)v.ten++;v.voters.add(b.voterCountryCode);map.set(e.targetCountryCode,v);}} return [...map.values()].sort((a,b)=>b.total-a.total||b.twelve-a.twelve||b.ten-a.ten||b.voters.size-a.voters.size||a.countryCode.localeCompare(b.countryCode)); }
  async syncScoreboard(guildId:string){const cfg=this.configs.get(guildId);if(!cfg.channels.scoreboard)return;const ch=await this.channel(guildId,'scoreboard');const s=this.results.findCurrent(guildId);const rows=s&&s.currentIndex>0?this.totals(s).map((r,i)=>`${i+1}. ${getCountry(r.countryCode)?.flag??'🌍'} ${getCountry(r.countryCode)?.nameTr??r.countryCode} — **${r.total}**`):[];const embed=new EmbedBuilder().setTitle('🏆 Canlı Puan Durumu').setDescription(rows.join('\n')||'Sonuçlar henüz açıklanmadı.').setColor(0x5865f2);let msg=cfg.messages.scoreboard?await ch.messages.fetch(cfg.messages.scoreboard).catch(()=>null):null;if(msg)await msg.edit({embeds:[embed]});else{msg=await ch.send({embeds:[embed]});await this.configs.setMessageId(guildId,'scoreboard',msg.id);}}
  private async announceWinner(guildId:string,s:ResultSession,ch:TextChannel){const w=this.totals(s,false)[0];if(!w)return;const country=getCountry(w.countryCode);const song=this.submissions.findApprovedByCountry(guildId,w.countryCode);await ch.send({embeds:[new EmbedBuilder().setTitle('🏆 FAN SONG CONTEST KAZANANI').setDescription(`## ${country?.flag??'🌍'} ${country?.nameTr.toLocaleUpperCase('tr')??w.countryCode}\n${song?`**${song.youtubeChannelName} — ${song.songTitle}**`:''}\nToplam: **${w.total} puan**`).setColor(0xf1c40f)]});const roleId=this.configs.get(guildId).roles.winner;const assignment=this.assignments.findActiveByCountry(guildId,w.countryCode);if(roleId&&assignment){const guild=await this.client.guilds.fetch(guildId);const member=await guild.members.fetch(assignment.discordUserId).catch(()=>null);const role=await guild.roles.fetch(roleId).catch(()=>null);if(member&&role&&!member.roles.cache.has(role.id))await member.roles.add(role,'Yarışma kazananı').catch(()=>undefined);}}
  private async channel(guildId:string,key:'results'|'scoreboard'){const id=this.configs.get(guildId).channels[key];const ch=id?await this.client.channels.fetch(id):null;if(!ch||ch.type!==ChannelType.GuildText||ch.guildId!==guildId)throw new Error(`${key.toUpperCase()}_CHANNEL_MISSING`);return ch;}
}
