import {afterAll,beforeAll,describe,expect,it} from 'vitest';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {openDatabase,closeDatabase} from '../src/database/connection.js';import {migrate} from '../src/database/migrate.js';import {VoteRepository} from '../src/database/voteRepository.js';import {ResultRepository} from '../src/database/resultRepository.js';import {SubmissionRepository} from '../src/database/submissionRepository.js';import {SongChangeRequestRepository} from '../src/database/songChangeRequestRepository.js';import type {YouTubeVideo} from '../src/types/youtube.js';
const dir=mkdtempSync(join(tmpdir(),'nexavision-result-'));const guild='123456789012345678';const votes=new VoteRepository();const results=new ResultRepository();const submissions=new SubmissionRepository();const changes=new SongChangeRequestRepository();
const video=(id:string):YouTubeVideo=>({videoId:id,canonicalUrl:`https://youtu.be/${id}`,title:id,channelTitle:'Artist',thumbnailUrl:null,viewCount:5,duration:'PT3M',publishedAt:'2025-01-01T00:00:00Z',liveBroadcastContent:'none'});
beforeAll(()=>migrate(openDatabase(join(dir,'test.sqlite'))));afterAll(()=>{closeDatabase();rmSync(dir,{recursive:true,force:true});});
describe('result snapshot ve song change atomikliği',()=>{
 it('reveal order ve index restart sonrasında değişmez',()=>{for(const [user,country,target] of [['111111111111111111','DK','SE'],['222222222222222222','SE','DK']]){const b=votes.beginDraft(guild,user!,country!);votes.submitDraft(b,[{points:12,targetCountryCode:target!}]);}const prepared=results.prepare(guild,votes.listSubmitted(guild));expect(results.transition(guild,'PREPARED','RUNNING')).toBe(true);const first=results.next(guild)!;const reloaded=new ResultRepository().findCurrent(guild)!;expect(reloaded.revealOrder).toEqual(prepared.revealOrder);expect(reloaded.currentIndex).toBe(1);const second=results.next(guild)!;expect(second.ballot.voterCountryCode).not.toBe(first.ballot.voterCountryCode);expect(second.finished).toBe(true);});
 it('onaylı change request eski entryyi history olarak saklar',()=>{const participant={guildId:guild,discordUserId:'333333333333333333',countryCode:'TR',countryName:'Türkiye',countryFlag:'🇹🇷'};const old=submissions.createPending(guild,participant,video('aaaaaaaaaaa'));expect(submissions.approveIfPending(old.id,'999999999999999999',5)).toBe(true);const req=changes.create(guild,'TR',participant.discordUserId,old.id,video('bbbbbbbbbbb'));const newId=changes.approve(req.id,'999999999999999999');expect(newId).toBeTypeOf('number');expect(submissions.findById(old.id)?.status).toBe('REJECTED');expect(submissions.findById(newId!)!).toMatchObject({status:'APPROVED',locked:true,replacesSubmissionId:old.id});expect(changes.findById(req.id)?.status).toBe('APPROVED');});
});
