import { getCountry } from "../config/countries.js";
import type { YouTubeVideo } from "../types/youtube.js";
import { getDatabase } from "./connection.js";

export interface SongChangeRequest {id:number;guildId:string;countryCode:string;requestedBy:string;currentSubmissionId:number;video:YouTubeVideo;status:'PENDING'|'APPROVED'|'REJECTED';submittedAt:string;reviewedAt:string|null;reviewedBy:string|null;rejectionReason:string|null;adminChannelId:string|null;adminMessageId:string|null}
interface Row {id:number;guild_id:string;country_code:string;requested_by:string;current_submission_id:number;proposed_youtube_video_id:string;proposed_youtube_url:string;proposed_song_title:string;proposed_channel_name:string;proposed_thumbnail_url:string|null;proposed_view_count:number;proposed_duration:string;proposed_published_at:string;status:'PENDING'|'APPROVED'|'REJECTED';submitted_at:string;reviewed_at:string|null;reviewed_by:string|null;rejection_reason:string|null;admin_channel_id:string|null;admin_message_id:string|null}
function fromRow(r:Row):SongChangeRequest{return{id:r.id,guildId:r.guild_id,countryCode:r.country_code,requestedBy:r.requested_by,currentSubmissionId:r.current_submission_id,video:{videoId:r.proposed_youtube_video_id,canonicalUrl:r.proposed_youtube_url,title:r.proposed_song_title,channelTitle:r.proposed_channel_name,thumbnailUrl:r.proposed_thumbnail_url,viewCount:r.proposed_view_count,duration:r.proposed_duration,publishedAt:r.proposed_published_at,liveBroadcastContent:'none'},status:r.status,submittedAt:r.submitted_at,reviewedAt:r.reviewed_at,reviewedBy:r.reviewed_by,rejectionReason:r.rejection_reason,adminChannelId:r.admin_channel_id,adminMessageId:r.admin_message_id};}
export class SongChangeRequestRepository {
 findById(id:number){const r=getDatabase().prepare('SELECT * FROM song_change_requests WHERE id=?').get(id) as Row|undefined;return r?fromRow(r):null;}
 hasPending(g:string,c:string){return Boolean(getDatabase().prepare("SELECT 1 FROM song_change_requests WHERE guild_id=? AND country_code=? AND status='PENDING'").get(g,c));}
 create(g:string,c:string,u:string,current:number,v:YouTubeVideo){const now=new Date().toISOString();const r=getDatabase().prepare(`INSERT INTO song_change_requests(guild_id,country_code,requested_by,current_submission_id,proposed_youtube_video_id,proposed_youtube_url,proposed_song_title,proposed_channel_name,proposed_thumbnail_url,proposed_view_count,proposed_duration,proposed_published_at,status,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'PENDING',?)`).run(g,c,u,current,v.videoId,v.canonicalUrl,v.title,v.channelTitle,v.thumbnailUrl,v.viewCount,v.duration,v.publishedAt,now);return this.findById(Number(r.lastInsertRowid))!;}
 attachMessage(id:number,c:string,m:string){getDatabase().prepare('UPDATE song_change_requests SET admin_channel_id=?,admin_message_id=? WHERE id=?').run(c,m,id);}
 reject(id:number,admin:string,reason:string){return getDatabase().prepare("UPDATE song_change_requests SET status='REJECTED',reviewed_at=?,reviewed_by=?,rejection_reason=? WHERE id=? AND status='PENDING'").run(new Date().toISOString(),admin,reason,id).changes===1;}
 approve(id:number,admin:string):number|null{const db=getDatabase();return db.transaction(()=>{const r=db.prepare('SELECT * FROM song_change_requests WHERE id=?').get(id) as Row|undefined;if(!r||r.status!=='PENDING')return null;const old=db.prepare("SELECT * FROM song_submissions WHERE id=? AND guild_id=? AND country_code=? AND status='APPROVED' AND locked=1").get(r.current_submission_id,r.guild_id,r.country_code) as {id:number;discord_user_id:string}|undefined;if(!old)throw new Error('CURRENT_ENTRY_CHANGED');if(db.prepare("SELECT 1 FROM song_submissions WHERE guild_id=? AND youtube_video_id=? AND status='APPROVED'").get(r.guild_id,r.proposed_youtube_video_id))throw new Error('DUPLICATE_VIDEO');const now=new Date().toISOString();db.prepare("UPDATE song_submissions SET status='REJECTED',locked=0,rejection_reason='Şarkı değişiklik talebi onaylandı.',reviewed_at=?,reviewed_by=? WHERE id=?").run(now,admin,old.id);const country=getCountry(r.country_code)!;const inserted=db.prepare(`INSERT INTO song_submissions(guild_id,discord_user_id,country_code,country_name,country_flag,youtube_video_id,youtube_url,song_title,youtube_channel_name,thumbnail_url,view_count_at_submission,view_count_at_approval,duration,published_at,status,submitted_at,reviewed_at,reviewed_by,locked,replaces_submission_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'APPROVED',?,?,?,1,?)`).run(r.guild_id,r.requested_by,r.country_code,country.nameTr,country.flag,r.proposed_youtube_video_id,r.proposed_youtube_url,r.proposed_song_title,r.proposed_channel_name,r.proposed_thumbnail_url,r.proposed_view_count,r.proposed_view_count,r.proposed_duration,r.proposed_published_at,r.submitted_at,now,admin,old.id);db.prepare("UPDATE song_change_requests SET status='APPROVED',reviewed_at=?,reviewed_by=? WHERE id=? AND status='PENDING'").run(now,admin,id);return Number(inserted.lastInsertRowid);})();}
 revertApproval(requestId:number,newSubmissionId:number):void{const db=getDatabase();db.transaction(()=>{const req=db.prepare('SELECT * FROM song_change_requests WHERE id=?').get(requestId) as Row|undefined;const fresh=db.prepare('SELECT replaces_submission_id FROM song_submissions WHERE id=?').get(newSubmissionId) as {replaces_submission_id:number|null}|undefined;if(!req||req.status!=='APPROVED'||!fresh?.replaces_submission_id)return;db.prepare("UPDATE song_submissions SET status='REJECTED',locked=0,rejection_reason='Resmi mesaj güncellenemedi; değişiklik geri alındı.' WHERE id=? AND status='APPROVED'").run(newSubmissionId);db.prepare("UPDATE song_submissions SET status='APPROVED',locked=1,rejection_reason=NULL WHERE id=? AND status='REJECTED'").run(fresh.replaces_submission_id);db.prepare("UPDATE song_change_requests SET status='PENDING',reviewed_at=NULL,reviewed_by=NULL WHERE id=?").run(requestId);})();}
}
